# =============================================================================
# datainsights.py -- Dataset Exploration & Insights Report
# =============================================================================
# Generates a comprehensive text report about the raw dataset including:
#   - Shape, columns, and data types
#   - Missing values and duplicate analysis
#   - Descriptive statistics for all numeric features
#   - Value ranges and distributions
#   - Unique counts for categorical/text columns
#   - Feature correlation highlights
#   - Top genres and artists
#   - Outlier detection summary
#
# Output is saved to: outputs/data_insights_output.txt
# =============================================================================

import sys
import os
import io

# Ensure project root is on the path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import pandas as pd
import numpy as np

from src.utils import RAW_DATASET_PATH, CLUSTERING_FEATURES, OUTPUTS_DIR


# ---------------------------------------------------------------------------
# Output file path
# ---------------------------------------------------------------------------
OUTPUT_PATH = os.path.join(OUTPUTS_DIR, "data_insights_output.txt")
os.makedirs(OUTPUTS_DIR, exist_ok=True)


def write_section(f, title, width=72):
    """Write a formatted section header."""
    f.write("\n" + "=" * width + "\n")
    f.write(f"  {title}\n")
    f.write("=" * width + "\n\n")


def write_subsection(f, title):
    """Write a formatted sub-section header."""
    f.write(f"\n--- {title} ---\n\n")


def generate_insights():
    """Generate the full data insights report and write to file."""

    # Load data
    df = pd.read_csv(RAW_DATASET_PATH)

    # Also capture to console via tee
    buffer = io.StringIO()

    def w(text=""):
        """Write to both buffer and console."""
        buffer.write(text + "\n")
        print(text)

    # ==================================================================
    # HEADER
    # ==================================================================
    w("=" * 72)
    w("  AMAZON MUSIC CLUSTERING -- DATA INSIGHTS REPORT")
    w("=" * 72)
    w(f"\n  Dataset : {RAW_DATASET_PATH}")
    w(f"  Generated by : datainsights.py")
    w()

    # ==================================================================
    # 1. DATASET OVERVIEW
    # ==================================================================
    w("=" * 72)
    w("  1. DATASET OVERVIEW")
    w("=" * 72)
    w()
    w(f"  Total Rows    : {df.shape[0]:,}")
    w(f"  Total Columns : {df.shape[1]}")
    w(f"  Memory Usage  : {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
    w()
    w("  Column List:")
    for i, col in enumerate(df.columns, 1):
        w(f"    {i:2d}. {col}")
    w()

    # ==================================================================
    # 2. DATA TYPES
    # ==================================================================
    w("=" * 72)
    w("  2. DATA TYPES")
    w("=" * 72)
    w()
    w(f"  {'Column':<25s} {'Dtype':<15s} {'Non-Null Count':<15s}")
    w(f"  {'-'*25} {'-'*15} {'-'*15}")
    for col in df.columns:
        dtype = str(df[col].dtype)
        non_null = f"{df[col].notna().sum():,}"
        w(f"  {col:<25s} {dtype:<15s} {non_null:<15s}")
    w()

    # Numeric vs non-numeric
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    text_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()
    w(f"  Numeric columns  ({len(numeric_cols)}): {numeric_cols}")
    w(f"  Text columns     ({len(text_cols)}): {text_cols}")
    w()

    # ==================================================================
    # 3. MISSING VALUES
    # ==================================================================
    w("=" * 72)
    w("  3. MISSING VALUES ANALYSIS")
    w("=" * 72)
    w()
    missing = df.isnull().sum()
    total_missing = missing.sum()
    if total_missing == 0:
        w("  No missing values found in any column. [OK]")
    else:
        w(f"  {'Column':<25s} {'Missing':<10s} {'Percentage':<10s}")
        w(f"  {'-'*25} {'-'*10} {'-'*10}")
        for col, count in missing[missing > 0].items():
            pct = count / len(df) * 100
            w(f"  {col:<25s} {count:<10,} {pct:<10.2f}%")
    w()

    # ==================================================================
    # 4. DUPLICATE ROWS
    # ==================================================================
    w("=" * 72)
    w("  4. DUPLICATE ROWS ANALYSIS")
    w("=" * 72)
    w()
    dup_count = df.duplicated().sum()
    w(f"  Exact duplicate rows   : {dup_count:,}")
    if "id_songs" in df.columns:
        dup_ids = df["id_songs"].duplicated().sum()
        w(f"  Duplicate song IDs     : {dup_ids:,}")
    if "name_song" in df.columns:
        dup_names = df["name_song"].duplicated().sum()
        w(f"  Duplicate song names   : {dup_names:,} (may include covers/remixes)")
    w()

    # ==================================================================
    # 5. DESCRIPTIVE STATISTICS
    # ==================================================================
    w("=" * 72)
    w("  5. DESCRIPTIVE STATISTICS (Numeric Columns)")
    w("=" * 72)
    w()

    desc = df[numeric_cols].describe().round(4)
    desc_str = desc.to_string()
    for line in desc_str.split("\n"):
        w("  " + line)
    w()

    # ==================================================================
    # 6. CLUSTERING FEATURE ANALYSIS
    # ==================================================================
    w("=" * 72)
    w("  6. CLUSTERING FEATURE DEEP-DIVE")
    w("=" * 72)
    w()
    w("  These 10 audio features are used for clustering:")
    w()

    available_features = [f for f in CLUSTERING_FEATURES if f in df.columns]

    for feature in available_features:
        col = df[feature]
        w(f"  >> {feature}")
        w(f"     Range       : {col.min():.4f}  to  {col.max():.4f}")
        w(f"     Mean        : {col.mean():.4f}")
        w(f"     Median      : {col.median():.4f}")
        w(f"     Std Dev     : {col.std():.4f}")
        w(f"     Skewness    : {col.skew():.4f}")
        w(f"     Kurtosis    : {col.kurtosis():.4f}")

        # IQR-based outlier detection
        q1 = col.quantile(0.25)
        q3 = col.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr
        outliers = ((col < lower) | (col > upper)).sum()
        w(f"     IQR         : {iqr:.4f}")
        w(f"     Outliers    : {outliers:,} ({outliers/len(df)*100:.1f}%)")
        w()

    # ==================================================================
    # 7. FEATURE CORRELATIONS
    # ==================================================================
    w("=" * 72)
    w("  7. FEATURE CORRELATIONS (|r| > 0.3)")
    w("=" * 72)
    w()

    corr = df[available_features].corr()
    pairs = []
    for i in range(len(available_features)):
        for j in range(i + 1, len(available_features)):
            r = corr.iloc[i, j]
            if abs(r) > 0.3:
                pairs.append((available_features[i], available_features[j], r))

    pairs.sort(key=lambda x: abs(x[2]), reverse=True)

    if pairs:
        w(f"  {'Feature 1':<20s} {'Feature 2':<20s} {'Correlation':<12s} {'Strength'}")
        w(f"  {'-'*20} {'-'*20} {'-'*12} {'-'*12}")
        for col1, col2, r in pairs:
            strength = "STRONG" if abs(r) > 0.5 else "MODERATE"
            direction = "+" if r > 0 else "-"
            w(f"  {col1:<20s} {col2:<20s} {r:>+10.4f}   {direction} {strength}")
    else:
        w("  No notable correlations (|r| > 0.3) found.")
    w()

    # Full correlation matrix
    w("  Full Correlation Matrix:")
    w()
    corr_str = corr.round(3).to_string()
    for line in corr_str.split("\n"):
        w("  " + line)
    w()

    # ==================================================================
    # 8. CATEGORICAL / TEXT COLUMN ANALYSIS
    # ==================================================================
    w("=" * 72)
    w("  8. TEXT / CATEGORICAL COLUMN ANALYSIS")
    w("=" * 72)
    w()

    if "genres" in df.columns:
        w("  >> genres")
        unique_genres = df["genres"].nunique()
        w(f"     Unique genres : {unique_genres:,}")
        w(f"     Top 15 genres:")
        for genre, count in df["genres"].value_counts().head(15).items():
            pct = count / len(df) * 100
            w(f"       {count:>6,} ({pct:5.1f}%)  {genre}")
        w()

    if "name_artists" in df.columns:
        w("  >> Artists")
        unique_artists = df["name_artists"].nunique()
        w(f"     Unique artists : {unique_artists:,}")
        w(f"     Top 15 artists by track count:")
        for artist, count in df["name_artists"].value_counts().head(15).items():
            w(f"       {count:>5,} tracks  {artist}")
        w()

    if "release_date" in df.columns:
        w("  >> Release Dates")
        w(f"     Unique dates   : {df['release_date'].nunique():,}")
        w(f"     Earliest       : {df['release_date'].min()}")
        w(f"     Latest         : {df['release_date'].max()}")
        w()

    if "explicit" in df.columns:
        w("  >> Explicit Content")
        explicit_counts = df["explicit"].value_counts()
        for val, count in explicit_counts.items():
            label = "Explicit" if val == 1 else "Clean"
            pct = count / len(df) * 100
            w(f"     {label:<10s}: {count:>7,} ({pct:.1f}%)")
        w()

    # ==================================================================
    # 9. OUTLIER SUMMARY
    # ==================================================================
    w("=" * 72)
    w("  9. OUTLIER SUMMARY (IQR Method)")
    w("=" * 72)
    w()
    w(f"  {'Feature':<20s} {'Outlier Count':<15s} {'% of Data':<10s}")
    w(f"  {'-'*20} {'-'*15} {'-'*10}")

    total_outlier_rows = set()
    for feature in available_features:
        col = df[feature]
        q1 = col.quantile(0.25)
        q3 = col.quantile(0.75)
        iqr = q3 - q1
        mask = (col < q1 - 1.5 * iqr) | (col > q3 + 1.5 * iqr)
        outlier_count = mask.sum()
        total_outlier_rows.update(df.index[mask].tolist())
        pct = outlier_count / len(df) * 100
        w(f"  {feature:<20s} {outlier_count:<15,} {pct:<10.1f}%")

    w(f"\n  Total unique rows with at least 1 outlier: "
      f"{len(total_outlier_rows):,} ({len(total_outlier_rows)/len(df)*100:.1f}%)")
    w()

    # ==================================================================
    # 10. DATA QUALITY SUMMARY
    # ==================================================================
    w("=" * 72)
    w("  10. DATA QUALITY SUMMARY")
    w("=" * 72)
    w()
    w(f"  Missing values     : {'NONE' if total_missing == 0 else f'{total_missing:,}'}")
    w(f"  Duplicate rows     : {dup_count:,}")
    w(f"  Total rows         : {len(df):,}")
    w(f"  Total columns      : {len(df.columns)}")
    w(f"  Numeric features   : {len(numeric_cols)}")
    w(f"  Text features      : {len(text_cols)}")
    w(f"  Clustering features: {len(available_features)}")
    w(f"  Data quality       : {'GOOD -- Ready for clustering' if total_missing == 0 and dup_count == 0 else 'NEEDS CLEANING'}")
    w()
    w("=" * 72)
    w("  END OF DATA INSIGHTS REPORT")
    w("=" * 72)

    # ==================================================================
    # Save to file
    # ==================================================================
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(buffer.getvalue())

    print(f"\n[INFO] Data insights report saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    generate_insights()


